// -------------------------------------------------------------
// 
// File Name: moore_rtl\Stateflow_Moore_example\Moore_Chart.v
// 
// Generated by MATLAB 8.3 and HDL Coder 3.4
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Moore_Chart
// Source Path: Stateflow_Moore_example/Moore_Subsystem/Moore_Chart
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Moore_Chart
          (
           clk,
           rst_n,
           enb,
           a,
           b
          );


  input   clk;
  input   rst_n;
  input   enb;
  output  [63:0] a;  // double
  output  [63:0] b;  // double

  parameter IN_FINAL = 3'd0, IN_IDLE = 3'd1, IN_INITIAL = 3'd2, IN_SEQ1 = 3'd3, IN_SEQ2 = 3'd4;

  reg [2:0] is_Moore_Chart;  // uint8
  real a_1;  // double
  real b_1;  // double
  real a_reg;  // double
  real b_reg;  // double
  reg [2:0] is_Moore_Chart_next;  // enum type state_type_is_Moore_Chart (5 enums)
  real a_reg_next;  // double
  real b_reg_next;  // double


  always @(posedge clk or negedge rst_n)
    begin : Moore_Chart_1_process
      if (rst_n == 1'b0) begin
        is_Moore_Chart <= IN_INITIAL;
      end
      else begin
        if (enb) begin
          is_Moore_Chart <= is_Moore_Chart_next;
          a_reg <= a_reg_next;
          b_reg <= b_reg_next;
        end
      end
    end

  always @* begin
    is_Moore_Chart_next = is_Moore_Chart;
    a_reg_next = a_reg;
    b_reg_next = b_reg;

    case ( is_Moore_Chart)
      IN_FINAL :
        begin
        end
      IN_IDLE :
        begin
          a_reg_next = 0.0;
        end
      IN_INITIAL :
        begin
          a_reg_next = 0.0;
          b_reg_next = 0.0;
        end
      IN_SEQ1 :
        begin
          a_reg_next = 1.0;
          b_reg_next = b_reg + 1.0;
        end
    endcase


    case ( is_Moore_Chart)
      IN_FINAL :
        begin
          is_Moore_Chart_next = IN_IDLE;
        end
      IN_IDLE :
        begin
          is_Moore_Chart_next = IN_SEQ1;
        end
      IN_INITIAL :
        begin
          is_Moore_Chart_next = IN_IDLE;
        end
      IN_SEQ1 :
        begin
          is_Moore_Chart_next = IN_SEQ2;
        end
      default :
        begin
          is_Moore_Chart_next = IN_FINAL;
        end
    endcase

  end

  always @* a_1 = a_reg_next;
  always @* b_1 = b_reg_next;



  assign a = $realtobits(a_1);

  assign b = $realtobits(b_1);

endmodule  // Moore_Chart

