// -------------------------------------------------------------
// 
// File Name: moore_rtl\Stateflow_Moore_example\Moore_Subsystem.v
// 
// Generated by MATLAB 8.3 and HDL Coder 3.4
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.2
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0.2
// Out2                          ce_out        0.2
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Moore_Subsystem
// Source Path: Stateflow_Moore_example/Moore_Subsystem
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Moore_Subsystem
          (
           clk,
           rst_n,
           clk_enable,
           ce_out,
           Out1,
           Out2
          );


  input   clk;
  input   rst_n;
  input   clk_enable;
  output  ce_out;
  output  [63:0] Out1;  // double
  output  [63:0] Out2;  // double


  wire [63:0] a;  // ufix64
  wire [63:0] b;  // ufix64


  Moore_Chart   u_Moore_Chart   (.clk(clk),
                                 .rst_n(rst_n),
                                 .enb(clk_enable),
                                 .a(a),  // double
                                 .b(b)  // double
                                 );

  assign ce_out = clk_enable;

  assign Out1 = a;

  assign Out2 = b;

endmodule  // Moore_Subsystem

